# Numpy Array & Matrix

In [1]:
import numpy as np # import numpy package
one_d_array = np.array([ 1,2,3,4 ]) # create 1D array
print( one_d_array ) # printing 1d array

[1 2 3 4]


In [2]:
print(  type(one_d_array)  ) # type
print(  one_d_array.ndim   ) # dimension
print(  one_d_array.size   ) # size / total no of element
print(  one_d_array.shape  ) # (r,c)
print(  one_d_array.dtype  )

<class 'numpy.ndarray'>
1
4
(4,)
int32


In [3]:
two_d_array = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10,11,12]  ]) # create 2D array
print(two_d_array) #printing 2D array Note: (list = row)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
print( type(two_d_array) )
print( two_d_array.ndim  )
print( two_d_array.size  )
print( two_d_array.shape )
print( two_d_array.dtype )

<class 'numpy.ndarray'>
2
12
(4, 3)
int32


In [5]:
# one element matrix
mx_ones = np.ones((3, 4), dtype = int)   #( (r, c) , datatype )
print(mx_ones)
print(mx_ones.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [6]:
mx_zeros = np.zeros((3, 4), dtype=bool)
print(mx_zeros)

[[False False False False]
 [False False False False]
 [False False False False]]


In [7]:
# empty matrix : contain random values
mx_empty = np.empty((3, 4), dtype=None)
print(mx_empty)

[[1.28690176e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.11261502e-306 8.75983079e+164 7.42282215e-091 7.78961257e-071]
 [2.36588498e+179 1.60065950e+160 3.99910963e+252 8.34451503e-308]]


## arange

In [9]:
# np.arange( start, end, steps )
arr1 = np.arange(1,13) # [a, b)
print(arr1)
arr2 = np.arange(1, 13, 2)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11]


## linspace

In [10]:
#np.linspace(from, to, elements )
np.linspace(1,4,3)

array([1. , 2.5, 4. ])

## reshape 

In [11]:

#convert from one to another
print( arr1 )
ar_2d = arr1.reshape(3, 4) # a*b = element in orignal (r, c)
print(ar_2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
# 1-d to 2-d
ar_2d_2 = arr1.reshape( 4,3 )
print(ar_2d_2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
ar = np.arange(1, 13).reshape(2, 6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## flatten

In [14]:
# flaten from 2-d to 1-d array
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## transpose

In [15]:
print(ar_2d)
np.transpose(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Arithematic Operations

In [16]:

arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
# print arr1 and arr2
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Addition
print( arr1 + arr2 )
np.add(arr1, arr2) 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [18]:
# subtraction
print( arr1 - arr2 )
np.subtract(arr1, arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
#division
print( arr1 / arr2 )
np.divide(arr1, arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#multiplication
  # * element-wise
  
print( arr1 * arr2 )
np.multiply(arr1, arr2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
# @ matrix-multiplication 
print( arr1 @ arr2 )
np.dot(arr1, arr2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [22]:
# max() & min()
print(arr1)

print( arr1.max() ) #return max element
print( arr1.argmax() ) #return index of max element
print( arr1.max(axis = 0) ) # return max column wise
print( arr1.max(axis = 1) ) # return max row wise
print('..........................................')
print( arr1.min() ) #return min element
print( arr1.argmin() ) #return index of min element
print( arr1.min(axis = 0) ) #return min column wise
print( arr1.min(axis = 1) ) #return min row wise

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
8
[7 8 9]
[3 6 9]
..........................................
1
0
[1 2 3]
[1 4 7]


In [23]:
# sum(), mean(), sqrt(), std(), exp(), log(). log10() 
print( arr1 )
print('..............................................  sum')
print( np.sum(arr1) )
print('..............................................  sum column')
print( np.sum(arr1, axis=0) ) # axis=0 is sum column wise
print('..............................................  sum row')
print( np.sum(arr2, ) ) # axis=1 is sum row wise
print('..............................................  mean')
print( np.mean(arr1) ) # mean of whole matrix
print('..............................................  sqrt')
print( np.sqrt(arr1) ) # sqrt of every element
print('..............................................  std')
print( np.std(arr1)  ) # standard division
print('..............................................  exp')
print( np.exp(arr1)  ) # exponenet value of all
print('..............................................  log')
print( np.log(arr1)  ) # log value of eac
print('..............................................  log10')
print( np.log10(arr1)) # log base 10 value of each


[[1 2 3]
 [4 5 6]
 [7 8 9]]
..............................................  sum
45
..............................................  sum column
[12 15 18]
..............................................  sum row
45
..............................................  mean
5.0
..............................................  sqrt
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
..............................................  std
2.581988897471611
..............................................  exp
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
..............................................  log
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
..............................................  log10
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.

# slicing

In [24]:
mx = np.arange(1,101).reshape(10,10)
print( mx )

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [25]:
print( mx[0] )

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
print( mx[:2])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [27]:
print( mx[0:1] )  # (row , above colum
      # mx[r (from ,to), c]

[[ 1  2  3  4  5  6  7  8  9 10]]


In [28]:
print( mx[0:2])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [29]:
print( mx[1:3] )

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [30]:
print( mx[ :, 0:1] )   #  [ r:c , c:r ]

[[ 1]
 [11]
 [21]
 [31]
 [41]
 [51]
 [61]
 [71]
 [81]
 [91]]


In [31]:
print( mx[ :, 0:3] ) #  [ r:c , c:r ]
#    mx[ r from : to, c from : to ]

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]
 [51 52 53]
 [61 62 63]
 [71 72 73]
 [81 82 83]
 [91 92 93]]


In [32]:
print( mx[0:4 , 0:4] )  #  [ r:c , c:r ]

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


## Array Concatination and split

In [33]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [34]:
np.concatenate( (arr1, arr2, arr1), axis=0 )  #axis column

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
np.concatenate( (arr1, arr2, arr1 ), axis=1 ) # axis row wise

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [36]:
#split
np.split(arr1, 2) 

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [37]:
np.split(arr1, 2, axis=1) # axis=1 column wise

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

# random module

In [38]:
import random 

In [39]:
#  random.random
rd_num = np.random.random(1)
rd_2D_array =  np.random.random((3,3))  # inbetween 0-1
print(rd_num)
print(rd_2D_array)

[0.82594625]
[[0.43706164 0.3043061  0.5538097 ]
 [0.07448788 0.89438664 0.02664523]
 [0.87616442 0.39059867 0.08126335]]


In [40]:
#  random.randint
rd_no = np.random.randint(1,4)
rd_2D_arr = np.random.randint(1,4, (4,4)) #( (from, to), (r,c) )
rd_3D_arr = np.random.randint(1,4, (2,4,4))
 
print(rd_no)
print(rd_2D_arr)
print(rd_3D_arr)

1
[[2 2 1 2]
 [3 2 3 1]
 [3 2 2 2]
 [2 2 1 3]]
[[[1 3 1 1]
  [1 1 3 2]
  [2 3 3 2]
  [3 2 3 1]]

 [[2 3 3 2]
  [3 1 1 3]
  [3 1 3 2]
  [2 3 2 2]]]


In [41]:
# random.seed()  always give same random values
np.random.seed(10)
rd_3D_arr = np.random.randint(1,4, (2,4,4))
print(rd_3D_arr)

[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


In [42]:
# above rd_3D_arr have same values
np.random.seed(10)
rd_3D_arr = np.random.randint(1,4, (2,4,4))
print(rd_3D_arr)

[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


In [43]:
arr_2D = np.random.rand(3,3) # return  3 x 3 matrix
print(arr_2D)

[[0.13145815 0.41366737 0.77872881]
 [0.58390137 0.18263144 0.82608225]
 [0.10540183 0.28357668 0.06556327]]


In [44]:
# random.choice()
x = [1,2,3,4] # list
choice_from_x = np.random.choice(x) # retun random single item from sequence
print(choice_from_x )

2


In [45]:
for i in range(20):
    print(np.random.choice(x))

2
3
4
3
1
4
1
3
1
2
4
3
1
3
4
1
4
2
3
4
